version: '3.4'

services:
  bluewhales.security:
    image: ${DOCKER_REGISTRY}bluewhalessecurity
    build:
      context: .
      dockerfile: BlueWhales.Security\Dockerfile

  bluewhales.main:
    image: ${DOCKER_REGISTRY}bluewhalesmain
    build:
      context: .
      dockerfile: ..\BlueWhales.Main\Dockerfile

